spring.application.name=veema-computer

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/veema_computer_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.context-path=/api/v1

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.lk.ijse.veema_computer=DEBUG
logging.file.name=logs/veema-computer.log